<?php

$_t_player_types_skill_double = 
'
DROP TABLE IF EXISTS "Player_Type_Skill_Categories_Double";
CREATE TABLE Player_Type_Skill_Categories_Double (ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,idPlayer_Types INTEGER ,idSkill_Categories INTEGER ,DESCRIPTION VARCHAR(255) );
';

$_dat_skill_double =
"
INSERT INTO player_type_skill_categories_double VALUES (1, 1, 2, 'Human Lineman Agility');
INSERT INTO player_type_skill_categories_double VALUES (2, 1, 3, 'Human Lineman Passing');
INSERT INTO player_type_skill_categories_double VALUES (3, 1, 4, 'Human Lineman Strength');
INSERT INTO player_type_skill_categories_double VALUES (4, 2, 3, 'Human Catcher Passing');
INSERT INTO player_type_skill_categories_double VALUES (5, 2, 4, 'Human Catcher Strength');
INSERT INTO player_type_skill_categories_double VALUES (6, 3, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (7, 3, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (8, 4, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (9, 4, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (10, 5, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (11, 5, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (12, 5, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (13, 6, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (14, 6, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (15, 7, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (16, 7, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (17, 8, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (18, 8, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (19, 9, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (20, 9, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (21, 10, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (22, 10, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (23, 10, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (24, 11, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (25, 11, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (26, 12, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (27, 12, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (28, 13, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (29, 14, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (30, 14, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (31, 15, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (32, 15, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (33, 15, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (34, 16, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (35, 16, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (36, 16, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (37, 16, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (38, 17, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (39, 17, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (40, 17, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (41, 18, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (42, 18, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (43, 18, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (44, 19, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (45, 19, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (46, 19, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (47, 20, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (48, 20, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (49, 20, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (50, 20, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (51, 21, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (52, 21, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (53, 21, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (54, 22, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (55, 22, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (56, 22, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (57, 23, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (58, 23, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (59, 24, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (60, 24, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (61, 25, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (62, 25, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (63, 26, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (64, 26, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (65, 26, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (66, 27, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (67, 27, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (68, 27, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (69, 28, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (70, 28, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (71, 29, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (72, 29, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (73, 29, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (74, 30, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (75, 30, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (76, 30, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (77, 31, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (78, 31, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (79, 31, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (81, 32, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (82, 32, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (83, 33, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (84, 33, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (87, 34, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (88, 34, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (89, 34, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (90, 44, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (91, 44, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (92, 44, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (93, 45, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (94, 45, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (95, 45, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (96, 46, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (97, 46, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (98, 46, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (99, 47, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (100, 47, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (101, 48, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (102, 49, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (103, 49, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (104, 50, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (105, 50, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (106, 51, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (107, 51, 4, '');
";
?>