<?php

$_t_player_types_skill_double = 
'
DROP TABLE IF EXISTS "Player_Type_Skill_Categories_Double";
CREATE TABLE Player_Type_Skill_Categories_Double (ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,idPlayer_Types INTEGER ,idSkill_Categories INTEGER ,DESCRIPTION VARCHAR(255) );
';

$_dat_skill_double =
"
INSERT INTO player_type_skill_categories_double VALUES (1, 1, 2, 'Human Lineman Agility');
INSERT INTO player_type_skill_categories_double VALUES (2, 1, 3, 'Human Lineman Passing');
INSERT INTO player_type_skill_categories_double VALUES (3, 1, 4, 'Human Lineman Strength');
INSERT INTO player_type_skill_categories_double VALUES (4, 2, 3, 'Human Catcher Passing');
INSERT INTO player_type_skill_categories_double VALUES (5, 2, 4, 'Human Catcher Strength');
INSERT INTO player_type_skill_categories_double VALUES (6, 3, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (7, 3, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (8, 4, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (9, 4, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (10, 5, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (11, 5, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (12, 5, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (13, 6, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (14, 6, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (15, 7, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (16, 7, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (17, 8, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (18, 8, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (19, 9, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (20, 9, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (21, 10, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (22, 10, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (23, 10, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (24, 11, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (25, 11, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (26, 12, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (27, 12, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (28, 13, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (29, 14, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (30, 14, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (31, 15, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (32, 15, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (33, 15, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (34, 16, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (35, 16, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (36, 16, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (37, 16, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (38, 17, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (39, 17, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (40, 17, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (41, 18, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (42, 18, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (43, 18, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (44, 19, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (45, 19, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (46, 19, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (47, 20, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (48, 20, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (49, 20, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (50, 20, 5, '');
INSERT INTO player_type_skill_categories_double VALUES (51, 21, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (52, 21, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (53, 21, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (54, 22, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (55, 22, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (56, 22, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (57, 23, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (58, 23, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (59, 24, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (60, 24, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (61, 25, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (62, 25, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (63, 26, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (64, 26, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (65, 26, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (66, 27, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (67, 27, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (68, 27, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (69, 28, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (70, 28, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (71, 29, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (72, 29, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (73, 29, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (74, 30, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (75, 30, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (76, 30, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (77, 31, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (78, 31, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (79, 31, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (81, 32, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (82, 32, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (83, 33, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (84, 33, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (87, 34, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (88, 34, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (89, 34, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (90, 44, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (91, 44, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (92, 44, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (93, 45, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (94, 45, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (95, 45, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (96, 46, 2, '');
INSERT INTO player_type_skill_categories_double VALUES (97, 46, 1, '');
INSERT INTO player_type_skill_categories_double VALUES (98, 46, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (99, 47, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (100, 47, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (101, 48, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (102, 49, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (103, 49, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (104, 50, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (105, 50, 4, '');
INSERT INTO player_type_skill_categories_double VALUES (106, 51, 3, '');
INSERT INTO player_type_skill_categories_double VALUES (107, 51, 4, '');
";

global $settings;
if ($settings['leegmgr_cyanide_edition'] == 2) {
    $_dat_skill_double .= "
INSERT INTO player_type_skill_categories_double VALUES (108, 54, 2, 'Undead Skeleton Agility');
INSERT INTO player_type_skill_categories_double VALUES (109, 54, 4, 'Undead Skeleton Strength');
INSERT INTO player_type_skill_categories_double VALUES (111, 54, 3, 'Undead Skeleton Passing');
INSERT INTO player_type_skill_categories_double VALUES (112, 55, 2, 'Undead Zombie Agility');
INSERT INTO player_type_skill_categories_double VALUES (113, 55, 4, 'Undead Zombie Strength');
INSERT INTO player_type_skill_categories_double VALUES (114, 55, 3, 'Undead Zombie Passing');
INSERT INTO player_type_skill_categories_double VALUES (115, 56, 4, 'Undead Ghoul Strength');
INSERT INTO player_type_skill_categories_double VALUES (116, 56, 3, 'Undead Ghoul Passing');
INSERT INTO player_type_skill_categories_double VALUES (117, 57, 2, 'Undead Wright Agility');
INSERT INTO player_type_skill_categories_double VALUES (118, 57, 3, 'Undead Wright Passing');
INSERT INTO player_type_skill_categories_double VALUES (119, 58, 1, 'Undead Mummy General');
INSERT INTO player_type_skill_categories_double VALUES (120, 58, 2, 'Undead Mummy Agility');
INSERT INTO player_type_skill_categories_double VALUES (121, 58, 3, 'Undead Mummy Passing');
INSERT INTO player_type_skill_categories_double VALUES (136, 60, 1, 'Halfling Halfling General');
INSERT INTO player_type_skill_categories_double VALUES (137, 60, 4, 'Halfling Halfling Strength');
INSERT INTO player_type_skill_categories_double VALUES (138, 60, 3, 'Hafling Halfling Passing');
INSERT INTO player_type_skill_categories_double VALUES (139, 61, 2, 'Hafling Treeman Agility');
INSERT INTO player_type_skill_categories_double VALUES (140, 61, 1, 'Hafling Treeman General');
INSERT INTO player_type_skill_categories_double VALUES (141, 61, 3, 'Hafling Treeman Passing');
INSERT INTO player_type_skill_categories_double VALUES (142, 62, 2, 'Norse Lineman Agility');
INSERT INTO player_type_skill_categories_double VALUES (143, 62, 4, 'Norse Lineman Strength');
INSERT INTO player_type_skill_categories_double VALUES (144, 62, 3, 'Norse Lineman Passing');
INSERT INTO player_type_skill_categories_double VALUES (145, 63, 4, 'Norse Thrower Strength');
INSERT INTO player_type_skill_categories_double VALUES (146, 63, 2, 'Norse Thrower Agility');
INSERT INTO player_type_skill_categories_double VALUES (147, 64, 4, 'Norse Runner Strength');
INSERT INTO player_type_skill_categories_double VALUES (148, 64, 3, 'Norse Runner Passing');
INSERT INTO player_type_skill_categories_double VALUES (149, 65, 2, 'Norse Berserker Agility');
INSERT INTO player_type_skill_categories_double VALUES (150, 65, 3, 'Norse Berserker Passing');
INSERT INTO player_type_skill_categories_double VALUES (151, 66, 2, 'Norse Ulfwerener Agility');
INSERT INTO player_type_skill_categories_double VALUES (152, 66, 3, 'Norse Ulfwerener Passing');
INSERT INTO player_type_skill_categories_double VALUES (153, 67, 1, 'Norse Yhetee General');
INSERT INTO player_type_skill_categories_double VALUES (154, 67, 2, 'Norse Yhetee Agility');
INSERT INTO player_type_skill_categories_double VALUES (155, 67, 3, 'Norse Yhetee Passing');
INSERT INTO player_type_skill_categories_double VALUES (156, 68, 2, 'Amazon Linewoman Agility');
INSERT INTO player_type_skill_categories_double VALUES (157, 68, 3, 'Amazon Linewoman Passing');
INSERT INTO player_type_skill_categories_double VALUES (158, 68, 4, 'Amazon Linewoman Strength');
INSERT INTO player_type_skill_categories_double VALUES (159, 69, 2, 'Amazon Thrower Agility');
INSERT INTO player_type_skill_categories_double VALUES (160, 69, 4, 'Amazon Thrower Strength');
INSERT INTO player_type_skill_categories_double VALUES (161, 70, 3, 'Amazon Catcher Passing');
INSERT INTO player_type_skill_categories_double VALUES (162, 70, 4, 'Amazon Catcher Strength');
INSERT INTO player_type_skill_categories_double VALUES (163, 71, 2, 'Amazon Blitzer Agility');
INSERT INTO player_type_skill_categories_double VALUES (164, 71, 3, 'Amazon Blitzer Passing');
INSERT INTO player_type_skill_categories_double VALUES (165, 72, 3, 'Elf Lineman Passing');
INSERT INTO player_type_skill_categories_double VALUES (166, 72, 4, 'Elf Lineman Strength');
INSERT INTO player_type_skill_categories_double VALUES (167, 73, 4, 'Elf Thrower Strength');
INSERT INTO player_type_skill_categories_double VALUES (168, 74, 3, 'Elf Catcher Passing');
INSERT INTO player_type_skill_categories_double VALUES (169, 74, 4, 'Elf Catcher Strength');
INSERT INTO player_type_skill_categories_double VALUES (170, 75, 3, 'Elf Blitzer Passing');
INSERT INTO player_type_skill_categories_double VALUES (171, 75, 4, 'Elf Blitzer Strength');
INSERT INTO player_type_skill_categories_double VALUES (172, 77, 3, 'High Elf Lineman Passing');
INSERT INTO player_type_skill_categories_double VALUES (173, 77, 4, 'High Elf Lineman Strength');
INSERT INTO player_type_skill_categories_double VALUES (174, 78, 4, 'High Elf Thrower Strength');
INSERT INTO player_type_skill_categories_double VALUES (175, 79, 3, 'High Elf Catcher Passing');
INSERT INTO player_type_skill_categories_double VALUES (176, 79, 4, 'High Elf Catcher Strength');
INSERT INTO player_type_skill_categories_double VALUES (177, 80, 3, 'High Elf Blitzer Passing');
INSERT INTO player_type_skill_categories_double VALUES (178, 80, 4, 'High Elf Blitzer Strength');
INSERT INTO player_type_skill_categories_double VALUES (179, 81, 2, 'Khemri Skeleton Agility');
INSERT INTO player_type_skill_categories_double VALUES (180, 81, 3, 'Khemri Skeleton Passing');
INSERT INTO player_type_skill_categories_double VALUES (181, 81, 4, 'Khemri Skeleton Strength');
INSERT INTO player_type_skill_categories_double VALUES (182, 82, 2, 'Khemri Thro-Ra Agility');
INSERT INTO player_type_skill_categories_double VALUES (183, 82, 4, 'Khemri Thro-Ra Strength');
INSERT INTO player_type_skill_categories_double VALUES (184, 83, 2, 'Khemri Blitz-Ra Agility');
INSERT INTO player_type_skill_categories_double VALUES (185, 83, 3, 'Khemri Blitz-Ra Passing');
INSERT INTO player_type_skill_categories_double VALUES (186, 84, 1, 'Khemri Tomb Guardian General');
INSERT INTO player_type_skill_categories_double VALUES (187, 84, 2, 'Khemri Tomb Guardian Agility');
INSERT INTO player_type_skill_categories_double VALUES (188, 84, 3, 'Khemri Tomb Guardian Passing');
INSERT INTO player_type_skill_categories_double VALUES (189, 86, 2, 'Necromantic Zombie Agility');
INSERT INTO player_type_skill_categories_double VALUES (190, 86, 3, 'Necromantic Zombie Passing');
INSERT INTO player_type_skill_categories_double VALUES (191, 86, 4, 'Necromantic Zombie Strength');
INSERT INTO player_type_skill_categories_double VALUES (192, 87, 3, 'Necromantic Ghoul Passing');
INSERT INTO player_type_skill_categories_double VALUES (193, 87, 4, 'Necromantic Ghoul Strength');
INSERT INTO player_type_skill_categories_double VALUES (194, 88, 2, 'Necromantic Wight Agility');
INSERT INTO player_type_skill_categories_double VALUES (195, 88, 3, 'Necromantic Wight Passing');
INSERT INTO player_type_skill_categories_double VALUES (196, 89, 2, 'Necromantic Flesh Golem Agility');
INSERT INTO player_type_skill_categories_double VALUES (197, 89, 3, 'Necromantic Flesh Golem Passing');
INSERT INTO player_type_skill_categories_double VALUES (198, 90, 3, 'Necromantic Werewolf Passing');
INSERT INTO player_type_skill_categories_double VALUES (199, 90, 4, 'Necromantic Werewolf Strength');
INSERT INTO player_type_skill_categories_double VALUES (200, 91, 2, 'Nurgle Rotter Agility');
INSERT INTO player_type_skill_categories_double VALUES (201, 91, 3, 'Nurgle Rotter Passing');
INSERT INTO player_type_skill_categories_double VALUES (202, 91, 4, 'Nurgle Rotter Strength');
INSERT INTO player_type_skill_categories_double VALUES (203, 92, 2, 'Nurgle Pestigor Agility');
INSERT INTO player_type_skill_categories_double VALUES (204, 92, 3, 'Nurgle Pestigor Passing');
INSERT INTO player_type_skill_categories_double VALUES (205, 93, 2, 'Nurgle Warrior Agility');
INSERT INTO player_type_skill_categories_double VALUES (206, 93, 3, 'Nurgle Warrior Passing');
INSERT INTO player_type_skill_categories_double VALUES (207, 94, 1, 'Nurgle Beast of Nurgle General');
INSERT INTO player_type_skill_categories_double VALUES (208, 94, 2, 'Nurgle Beast of Nurgle Agility');
INSERT INTO player_type_skill_categories_double VALUES (209, 94, 3, 'Nurgle Beast of Nurgle Passing');
INSERT INTO player_type_skill_categories_double VALUES (210, 94, 5, 'Nurgle Beast of Nurgle Mutation');
INSERT INTO player_type_skill_categories_double VALUES (211, 95, 1, 'Ogre Snotling General');
INSERT INTO player_type_skill_categories_double VALUES (212, 95, 3, 'Ogre Snotling Passing');
INSERT INTO player_type_skill_categories_double VALUES (213, 95, 4, 'Ogre Snotling Strength');
INSERT INTO player_type_skill_categories_double VALUES (214, 96, 1, 'Ogre Ogre General');
INSERT INTO player_type_skill_categories_double VALUES (215, 96, 2, 'Ogre Ogre Agility');
INSERT INTO player_type_skill_categories_double VALUES (216, 96, 3, 'Ogre Ogre Passing');
INSERT INTO player_type_skill_categories_double VALUES (217, 97, 2, 'Vampire Thrall Agility');
INSERT INTO player_type_skill_categories_double VALUES (218, 97, 3, 'Vampire Thrall Passing');
INSERT INTO player_type_skill_categories_double VALUES (219, 97, 4, 'Vampire Thrall Strength');
INSERT INTO player_type_skill_categories_double VALUES (220, 98, 3, 'Vampire Vampire Passing');
INSERT INTO player_type_skill_categories_double VALUES (221, 107, 1, 'Goblin Bombardier General');
INSERT INTO player_type_skill_categories_double VALUES (222, 107, 3, 'Goblin Bombardier Passing');
INSERT INTO player_type_skill_categories_double VALUES (223, 107, 4, 'Goblin Bombardier Strength');
";
}
?>
