<?php

// Race defs
define('T_RACE_AMAZON', 0);
define('T_RACE_CHAOS', 1);
define('T_RACE_CHAOS_DWARF', 2);
define('T_RACE_DARK_ELF', 3);
define('T_RACE_DWARF', 4);
define('T_RACE_ELF', 5);
define('T_RACE_GOBLIN', 6);
define('T_RACE_HALFLING', 7);
define('T_RACE_HIGH_ELF', 8);
define('T_RACE_HUMAN', 9);
define('T_RACE_KHEMRI', 10);
define('T_RACE_LIZARDMAN', 11);
define('T_RACE_ORC', 12);
define('T_RACE_NECROMANTIC', 13);
define('T_RACE_NORSE', 14);
define('T_RACE_NURGLE', 15);
define('T_RACE_OGRE', 16);
define('T_RACE_UNDEAD', 17);
define('T_RACE_VAMPIRE', 18);
define('T_RACE_SKAVEN', 19);
define('T_RACE_WOOD_ELF', 20);

$DEA = array (
	'Amazon'	=> array (
		'other'	=> array (
			'rr_cost' => 50000,
			'icon' => 'amazon.png',
			'race_id' => T_RACE_AMAZON, # (Amazon)
		),
		'players'	=> array (
			'Linewoman'	=> array (
				'ma'        	=> 6,
				'st'        	=> 3,
				'ag'        	=> 3,
				'av'        	=> 7,
				'def'	    => array (23),
				'norm'		=> array ('G'),
				'doub'		=> array ('A', 'S', 'P'),
				'qty'			=> 16,
				'cost'			=> 50000,
				'icon'			=> 'amlineman1an',
			    'pos_id'        => 1,
			),
			'Thrower'	=> array (
				'ma'        	=> 6,
				'st'        	=> 3,
				'ag'        	=> 3,
				'av'        	=> 7,
				'def'	    => array (23, 45),
				'norm'		=> array ('G', 'P'),
				'doub'		=> array ('A', 'S'),
				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'amthrower1an',
			    'pos_id'        => 2,
			),
			'Catcher'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (23, 20),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'amcatcher1an',
			    'pos_id'        => 3,
			),
			'Blitzer'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (23, 1),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 90000,
				'icon'			=> 'amblitzer1an',
			    'pos_id'        => 4,
			)
		)
	),

	'Chaos'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'chaos.png',
			'race_id' => T_RACE_CHAOS, # (Chaos)
		),
		'players'	=> array (
			'Beastman'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (75),
 				'norm'		=> array ('G', 'S', 'M'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 16,
				'cost'			=> 60000,
				'icon'			=> 'cbeastman1an',
			    'pos_id'        => 10,
			),
			'Chaos Warrior'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 4,
 				'ag'        	=> 3,
 				'av'        	=> 9,
 				'def'	    => array (),
 				'norm'		=> array ('G', 'S', 'M'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 100000,
				'icon'			=> 'cwarrior4an',
			    'pos_id'        => 11,
			),
			'Minotaur'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 5,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (99, 5, 75, 54, 59, 112),
 				'norm'		=> array ('S', 'M'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 150000,
				'icon'			=> 'minotaur2an',
			    'pos_id'        => 12,
			)
		)	
	),
	
	'Chaos Dwarf'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'chaosdwarf.png',
			'race_id' => T_RACE_CHAOS_DWARF, # (Chaos Dwarf)
		),
		'players'	=> array (
			'Hobgoblin'	=> array (
				'ma'        	=> 6,
				'st'        	=> 3,
				'ag'        	=> 3,
				'av'        	=> 7,
				'def'	    => array (),
				'norm'		=> array ('G'),
				'doub'		=> array ('A', 'S', 'P'),
				'qty'			=> 16,
				'cost'			=> 40000,
				'icon'			=> 'cdhobgoblin1an',
			    'pos_id'        => 20,
			),
			'Chaos Dwarf Blocker'	=> array (
				'ma'        	=> 4,
				'st'        	=> 3,
				'ag'        	=> 2,
				'av'        	=> 9,
				'def'	    => array (1, 13, 59),
				'norm'		=> array ('G', 'S'),
				'doub'		=> array ('A', 'P', 'M'),
				'qty'			=> 6,
				'cost'			=> 70000,
				'icon'			=> 'cddwarf1an',
			    'pos_id'        => 21,
			),
			'Bull Centaur'	=> array (
				'ma'        	=> 6,
				'st'        	=> 4,
				'ag'        	=> 2,
				'av'        	=> 9,
				'def'	    => array (28, 29, 59),
				'norm'		=> array ('G', 'S'),
				'doub'		=> array ('A', 'P'),
				'qty'			=> 2,
				'cost'			=> 130000,
				'icon'			=> 'centaur1an',
			    'pos_id'        => 22,
			),
			'Minotaur'	=> array (
				'ma'        	=> 5,
				'st'        	=> 5,
				'ag'        	=> 2,
				'av'        	=> 8,
				'def'	    => array (99, 5, 75, 54, 59, 112),
				'norm'		=> array ('S'),
				'doub'		=> array ('G', 'A', 'P', 'M'),
				'qty'			=> 1,
				'cost'			=> 150000,
				'icon'			=> 'minotaur2an',
			    'pos_id'        => 23,
			)
		)
	),

	'Dark Elf'	=> array (
		'other'	=> array (
			'rr_cost' => 50000,
			'icon' => 'darkelf.png',
			'race_id' => T_RACE_DARK_ELF, # (Dark Elf)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 8,
 				'def'	    => array (),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 70000,
				'icon'			=> 'delineman1an',
			    'pos_id'        => 30,
			),
			'Runner'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (41),
 				'norm'		=> array ('G', 'A', 'P'),
 				'doub'		=> array ('S'),
 				'qty'			=> 2,
				'cost'			=> 80000,
				'icon'			=> 'deblitzer1',
			    'pos_id'        => 31,
			),
			'Assassin'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (10, 106),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'delineman1',
			    'pos_id'        => 32,
			),
			'Blitzer'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 8,
 				'def'	    => array (1),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 4,
				'cost'			=> 100000,
				'icon'			=> 'deblitzer1an',
			    'pos_id'        => 33,
			),
			'Witch Elf'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (5, 23, 24),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 110000,
				'icon'			=> 'dewitchelf1an',
			    'pos_id'        => 34,
			)
		)
	),
	
	'Dwarf'	=> array (
		'other'	=> array (
			'rr_cost' => 40000,
			'icon' => 'dwarf.png',
			'race_id' => T_RACE_DWARF, # (Dwarf)
		),
		'players'	=> array (
			'Blocker'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 9,
 				'def'	    => array (1, 13, 59),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 16,
				'cost'			=> 70000,
				'icon'			=> 'dlongbeard1an',
			    'pos_id'        => 40,
			),
			'Runner'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (12, 59),
 				'norm'		=> array ('G', 'P'),
 				'doub'		=> array ('A', 'S'),
 				'qty'			=> 2,
				'cost'			=> 80000,
				'icon'			=> 'drunner1an',
			    'pos_id'        => 41,
			),
			'Blitzer'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 9,
 				'def'	    => array (1, 59),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 80000,
				'icon'			=> 'dblitzer1an',
			    'pos_id'        => 42,
			),
			'Troll Slayer'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (1, 2, 5, 59),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'dslayer1an',
			    'pos_id'        => 43,
			),
			'Deathroller'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 7,
 				'ag'        	=> 1,
 				'av'        	=> 10,
 				'def'	    => array (50, 3, 53, 54, 100, 105, 57),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 160000,
				'icon'			=> 'ddeathroller1an',
			    'pos_id'        => 44,
			)
		)
	),
	
	'Elf'	=> array (
		'other'	=> array (
			'rr_cost' => 50000,
			'icon' => 'elf.png',
			'race_id' => T_RACE_ELF, # (Elf)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 6,
				'st'        	=> 3,
				'ag'        	=> 4,
				'av'        	=> 7,
				'def'	    => array (),
				'norm'		=> array ('G', 'A'),
				'doub'		=> array ('S', 'P'),
				'qty'			=> 16,
				'cost'			=> 60000,
				'icon'			=> 'welineman1an',
			    'pos_id'        => 50,
			),
			'Thrower'	=> array (
				'ma'        	=> 6,
				'st'        	=> 3,
				'ag'        	=> 4,
				'av'        	=> 7,
    			'def'	    => array (45),
				'norm'		=> array ('G', 'A', 'P'),
				'doub'		=> array ('S'),
				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'wethrower1an',
			    'pos_id'        => 51,
			),
			'Catcher'	=> array (
				'ma'        	=> 8,
				'st'        	=> 3,
				'ag'        	=> 4,
				'av'        	=> 7,
				'def'	    => array (20, 44),
				'norm'		=> array ('G', 'A'),
				'doub'		=> array ('S', 'P'),
				'qty'			=> 4,
				'cost'			=> 100000,
				'icon'			=> 'wecatcher1an',
			    'pos_id'        => 52,
			),
			'Blitzer'	=> array (
				'ma'        	=> 7,
				'st'        	=> 3,
				'ag'        	=> 4,
				'av'        	=> 8,
				'def'	    => array (1, 26),
				'norm'		=> array ('G', 'A'),
				'doub'		=> array ('S', 'P'),
				'qty'			=> 2,
				'cost'			=> 110000,
				'icon'			=> 'weblitzer1an',
			    'pos_id'        => 53,
			)
		)
	),
	
	'Goblin'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'goblin.png',
			'race_id' => T_RACE_GOBLIN, # (Goblin)
		),
		'players'	=> array (
			'Goblin'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (23, 104, 108),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 40000,
				'icon'			=> 'goblin4an',
			    'pos_id'        => 60,
			),
			'Bombardier'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (93, 23, 100, 105, 108),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 1,
				'cost'			=> 40000,
				'icon'			=> 'goblin3an',
			    'pos_id'        => 61,
			),
			'Pogoer'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (3, 23, 25, 105, 108, 79),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 1,
				'cost'			=> 40000,
				'icon'			=> 'goblin5an',
			    'pos_id'        => 62,
			),
			'Looney'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (95, 100, 105, 108),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 1,
				'cost'			=> 40000,
				'icon'			=> 'goblin2an',
			    'pos_id'        => 63,
			),
			'Fanatic'	=> array (
				'ma'        	=> 3,
 				'st'        	=> 7,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (91, 100, 105, 108),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 70000,
				'icon'			=> 'goball1an',
			    'pos_id'        => 64,
			),
			'Troll'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (99, 90, 54, 102, 103, 110),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G','A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 110000,
				'icon'			=> 'troll1an',
			    'pos_id'        => 65,
			)
		)
	),
	
	'Halfling'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'halfling.png',
			'race_id' => T_RACE_HALFLING, # (Halfling)
		),
		'players'	=> array (
			'Halfling'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 6,
 				'def'	    => array (23, 104, 108),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 30000,
				'icon'			=> 'halfling3an',
			    'pos_id'        => 70,
			),
			'Treeman'	=> array (
				'ma'        	=> 2,
 				'st'        	=> 6,
 				'ag'        	=> 1,
 				'av'        	=> 10,
 				'def'	    => array (99, 54, 57, 58, 109, 59, 110),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 120000,
				'icon'			=> 'treeman1an',
			    'pos_id'        => 71,
			)
		)
	),
	
	
	
	'High Elf'	=> array (
		'other'	=> array (
			'rr_cost' => 50000,
			'icon' => 'highelf.png',
			'race_id' => T_RACE_HIGH_ELF, # (High Elf)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 8,
 				'def'	    => array (),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 70000,
				'icon'			=> 'helineman1an',
			    'pos_id'        => 80,
			),
			'Thrower'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 8,
 				'def'	    => array (45, 46),
 				'norm'		=> array ('G', 'A', 'P'),
 				'doub'		=> array ('S'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'hethrower1an',
			    'pos_id'        => 81,
			),
			'Catcher'	=> array (
				'ma'        	=> 8,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (20),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 4,
				'cost'			=> 90000,
				'icon'			=> 'hecatcher1an',
			    'pos_id'        => 82,
			),
			'Blitzer'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 8,
 				'def'	    => array (1),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 100000,
				'icon'			=> 'heblitzer1an',
			    'pos_id'        => 83,
			)
		)
	),
	
	'Human'	=> array (
		'other'	=> array (
			'rr_cost' => 50000,
			'icon' => 'human.png',
			'race_id' => T_RACE_HUMAN, # (Human)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 50000,
				'icon'			=> 'hlineman1an',
			    'pos_id'        => 90,
			),
			'Catcher'	=> array (
				'ma'        	=> 8,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (20, 23),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 4,
				'cost'			=> 70000,
				'icon'			=> 'hcatcher1an',
			    'pos_id'        => 91,
			),
			'Thrower'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (12, 45),
 				'norm'		=> array ('G', 'P'),
 				'doub'		=> array ('A', 'S'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'hthrower1an',
			    'pos_id'        => 92,
			),
			'Blitzer'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (1),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 90000,
				'icon'			=> 'hblitzer1an',
			    'pos_id'        => 93,
			),
			'Ogre'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 5,
 				'ag'        	=> 2,
 				'av'        	=> 9,
 				'def'	    => array (99, 94, 54, 59, 110),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G','A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 140000,
				'icon'			=> 'ogre4an',
			    'pos_id'        => 94,
			)
		)
	),
	
	'Khemri'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'khemri.png',
			'race_id' => T_RACE_KHEMRI, # (Khemri)
		),
		'players'	=> array (
			'Skeleton'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 7,
 				'def'	    => array (103),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 30000,
				'icon'			=> 'kmskeleton1an',
			    'pos_id'        => 100,
			),
			'Thro-Ra'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 7,
 				'def'	    => array (45, 103, 12),
 				'norm'		=> array ('G', 'P'),
 				'doub'		=> array ('A', 'S'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'kmthrower1an',
			    'pos_id'        => 101,
			),
			'Blitz-Ra'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (1, 103),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'kmblitzer1an',
			    'pos_id'        => 102,
			),
			'Mummy'	=> array (
				'ma'        	=> 3,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (54, 103),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 110000,
				'icon'			=> 'kmmummy1an',
			    'pos_id'        => 103,
			)
		)
	),
	
	'Lizardman'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'lizardmen.png',
			'race_id' => T_RACE_LIZARDMAN, # (Lizardman)
		),
		'players'	=> array (
			'Skink'	=> array (
				'ma'        	=> 8,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (23, 108),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 60000,
				'icon'			=> 'lmskink1an',
			    'pos_id'        => 110,
			),
			'Saurus'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 4,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 6,
				'cost'			=> 80000,
				'icon'			=> 'lmsaurus1an',
			    'pos_id'        => 111,
			),
			'Kroxigor'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (99, 94, 54, 76, 59),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 140000,
				'icon'			=> 'kroxigor1an',
			    'pos_id'        => 112,
			)
		)
	),
	
	'Orc'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'orc.png',
			'race_id' => T_RACE_ORC, # (Orc)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 9,
 				'def'	    => array (),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 50000,
				'icon'			=> 'olineman1an',
			    'pos_id'        => 120,
			),
			'Goblin'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 2,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (104, 23, 108),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 4,
				'cost'			=> 40000,
				'icon'			=> 'goblin1an',
			    'pos_id'        => 121,
			),
			'Thrower'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (12, 45),
 				'norm'		=> array ('G', 'P'),
 				'doub'		=> array ('A', 'S'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'othrower1an',
			    'pos_id'        => 122,
			),
			'Black Orc Blocker'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 4,
 				'ag'        	=> 2,
 				'av'        	=> 9,
 				'def'	    => array (),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 80000,
				'icon'			=> 'oblackorc1an',
			    'pos_id'        => 123,
			),
			'Blitzer'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 9,
 				'def'	    => array (1),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 80000,
				'icon'			=> 'oblitzer1an',
			    'pos_id'        => 124,
			),
			'Troll'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (99, 90, 54, 102, 103, 110),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G','A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 110000,
				'icon'			=> 'troll1an',
			    'pos_id'        => 125,
			)
		)
	),
		
	'Necromantic'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'necromantic.png',
			'race_id' => T_RACE_NECROMANTIC, # (Necromantic)
		),
		'players'	=> array (
			'Zombie'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (103),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 40000,
				'icon'			=> 'uzombie1',
			    'pos_id'        => 130,
			),
			'Ghoul'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (23),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'ughoul1an',
			    'pos_id'        => 131,
			),
			'Wight'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (1, 103),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'uwight1an',
			    'pos_id'        => 132,
			),
			'Flesh Golem'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 4,
 				'ag'        	=> 2,
 				'av'        	=> 9,
 				'def'	    => array (103, 57, 59),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 110000,
				'icon'			=> 'ngolem1an',
			    'pos_id'        => 133,
			),
			'Werewolf'	=> array (
				'ma'        	=> 8,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (71, 5, 103),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 120000,
				'icon'			=> 'nwerewolf1an',
			    'pos_id'        => 134,
			)
		)
	),	
	
	'Norse'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'norse.png',
			'race_id' => T_RACE_NORSE, # (Norse)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (1),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 50000,
				'icon'			=> 'nlineman1an',
			    'pos_id'        => 140,
			),
			'Thrower'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (1, 45),
 				'norm'		=> array ('G', 'P'),
 				'doub'		=> array ('A', 'S'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'nthrower1an',
			    'pos_id'        => 141,
			),
			'Runner'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (1, 2),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'ncatcher1an',
			    'pos_id'        => 142,
			),
			'Berserker'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (1, 5, 24),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'ncatcher1an',
			    'pos_id'        => 143,
			),
			'Ulfwerener'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 4,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (5),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 110000,
				'icon'			=> 'nlineman2an',
			    'pos_id'        => 144,
			),
			'Snow Troll'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 8,
 				'def'	    => array (99, 71, 72, 5, 112),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 140000,
				'icon'			=> 'troll1an',
			    'pos_id'        => 145,
			)
		)
	),	
	
	'Nurgle'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'nurgle.png',
			'race_id' => T_RACE_NURGLE, # (Nurgle)
		),
		'players'	=> array (
			'Rotter'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (96, 101),
 				'norm'		=> array ('G', 'M'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 40000,
				'icon'			=> 'troll2an',
			    'pos_id'        => 150,
			),
			'Pestigor'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (75, 101, 103),
 				'norm'		=> array ('G', 'S', 'M'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 80000,
				'icon'			=> 'troll2an',
			    'pos_id'        => 151,
			),
			'Nurgle Warrior'=> array (
				'ma'        	=> 4,
 				'st'        	=> 4,
 				'ag'        	=> 2,
 				'av'        	=> 9,
 				'def'	    => array (72, 74, 101, 103),
 				'norm'		=> array ('G', 'S', 'M'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 4,
				'cost'			=> 110000,
				'icon'			=> 'troll2an',
			    'pos_id'        => 152,
			),
			'Beast of Nurgle'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (99, 72, 74, 54, 101, 102, 103, 77),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P', 'M'),
 				'qty'			=> 1,
				'cost'			=> 140000,
				'icon'			=> 'troll2an',
			    'pos_id'        => 153,
			)
		)
	),	
		
	'Ogre'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'ogros.png',
			'race_id' => T_RACE_OGRE, # (Ogre)
		),
		'players'	=> array (
			'Snotling'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 1,
 				'ag'        	=> 3,
 				'av'        	=> 5,
 				'def'	    => array (23, 104, 26, 108, 111),
 				'norm'		=> array ('A'),
 				'doub'		=> array ('G', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 20000,
				'icon'			=> 'goblin1an',
			    'pos_id'        => 160,
			),
			'Ogre'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 5,
 				'ag'        	=> 2,
 				'av'        	=> 9,
 				'def'	    => array (94, 54, 59, 110),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G','A', 'P'),
 				'qty'			=> 6,
				'cost'			=> 140000,
				'icon'			=> 'ogre4an',
			    'pos_id'        => 161,
			)
			
		)
	),	
	
	'Undead'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'undead.png',
			'race_id' => T_RACE_UNDEAD, # (Undead)
		),
		'players'	=> array (
			'Skeleton'	=> array (
				'ma'        	=> 5,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 7,
 				'def'	    => array (103),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 30000,
				'icon'			=> 'kmskeleton1an',
			    'pos_id'        => 170,
			),
			'Zombie'	=> array (
				'ma'        	=> 4,
 				'st'        	=> 3,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (103),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 40000,
				'icon'			=> 'uzombie2an',
			    'pos_id'        => 171,
			),
			'Ghoul'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (23),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 4,
				'cost'			=> 70000,
				'icon'			=> 'ughoul4an',
			    'pos_id'        => 172,
			),
			'Wight'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (1, 103),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'uwight2an',
			    'pos_id'        => 173,
			),
			'Mummy'	=> array (
				'ma'        	=> 3,
 				'st'        	=> 5,
 				'ag'        	=> 1,
 				'av'        	=> 9,
 				'def'	    => array (54, 103),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 2,
				'cost'			=> 110000,
				'icon'			=> 'uwight2an',
			    'pos_id'        => 174,
			)
		)
	),	
	
		
	'Vampire'	=> array (
		'other'	=> array (
			'rr_cost' => 70000,
			'icon' => 'vampire.png',
			'race_id' => T_RACE_VAMPIRE, # (Vampire)
		),
		'players'	=> array (
			'Thrall'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 40000,
				'icon'			=> 'vampire2an',
			    'pos_id'        => 180,
			),
			'Vampire'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 4,
 				'ag'        	=> 4,
 				'av'        	=> 8,
 				'def'	    => array (92, 98, 103),
 				'norm'		=> array ('G', 'A', 'S'),
 				'doub'		=> array ('P'),
 				'qty'			=> 6,
				'cost'			=> 110000,
				'icon'			=> 'vampire1an',
			    'pos_id'        => 181,
			)
		)
	),
		
		
	'Skaven'	=> array (
		'other'	=> array (
			'rr_cost' => 60000,
			'icon' => 'skaven.png',
			'race_id' => T_RACE_SKAVEN, # (Skaven)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (),
 				'norm'		=> array ('G'),
 				'doub'		=> array ('A', 'S', 'P', 'M'),
 				'qty'			=> 16,
				'cost'			=> 50000,
				'icon'			=> 'sklineman1an',
			    'pos_id'        => 190,
			),
			'Thrower'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 7,
 				'def'	    => array (45, 12),
 				'norm'		=> array ('G', 'P'),
 				'doub'		=> array ('A', 'S', 'M'),
 				'qty'			=> 2,
				'cost'			=> 70000,
				'icon'			=> 'skthrower1an',
			    'pos_id'        => 191,
			),
			'Gutter Runner'	=> array (
				'ma'        	=> 9,
 				'st'        	=> 2,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (23),
 				'norm'		=> array ('G', 'A'),
 				'doub'		=> array ('S', 'P', 'M'),
 				'qty'			=> 4,
				'cost'			=> 80000,
				'icon'			=> 'skrunner1an',
			    'pos_id'        => 192,
			),
			'Blitzer'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 3,
 				'av'        	=> 8,
 				'def'	    => array (1),
 				'norm'		=> array ('G', 'S'),
 				'doub'		=> array ('A', 'P', 'M'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'skstorm1an',
			    'pos_id'        => 193,
			),
			'Rat Ogre'	=> array (
				'ma'        	=> 6,
 				'st'        	=> 5,
 				'ag'        	=> 2,
 				'av'        	=> 8,
 				'def'	    => array (99, 5, 54, 76, 112),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G','A', 'P', 'M'),
 				'qty'			=> 1,
				'cost'			=> 160000,
				'icon'			=> 'ratogre1an',
			    'pos_id'        => 194,
			)
		)
	),
	
	'Wood Elf'	=> array (
		'other'	=> array (
			'rr_cost' => 50000,
			'icon' => 'woodelf.png',
			'race_id' => T_RACE_WOOD_ELF, # (Wood Elf)
		),
		'players'	=> array (
			'Lineman'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (),
 				'norm'		=> array ('A', 'G'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 16,
				'cost'			=> 70000,
				'icon'			=> 'welineman1an',
			    'pos_id'        => 200,
			),
			'Catcher'	=> array (
				'ma'        	=> 9,
 				'st'        	=> 2,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (20,23),
 				'norm'		=> array ('A', 'G'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 4,
				'cost'			=> 90000,
				'icon'			=> 'wecatcher1an',
			    'pos_id'        => 201,
			),
			'Thrower'	=> array (
				'ma'        	=> 7,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (45),
 				'norm'		=> array ('A', 'G', 'P'),
 				'doub'		=> array ('S'),
 				'qty'			=> 2,
				'cost'			=> 90000,
				'icon'			=> 'wethrower1an',
			    'pos_id'        => 202,
			),
			'Wardancer'	=> array (
				'ma'        	=> 8,
 				'st'        	=> 3,
 				'ag'        	=> 4,
 				'av'        	=> 7,
 				'def'	    => array (1, 23, 25),
 				'norm'		=> array ('A', 'G'),
 				'doub'		=> array ('S', 'P'),
 				'qty'			=> 2,
				'cost'			=> 120000,
				'icon'			=> 'weblitzer1an',
			    'pos_id'        => 203,
			),
			'Treeman'	=> array (
				'ma'        	=> 2,
 				'st'        	=> 6,
 				'ag'        	=> 1,
 				'av'        	=> 10,
 				'def'	    => array (99, 54, 57, 58, 109, 59, 110),
 				'norm'		=> array ('S'),
 				'doub'		=> array ('G', 'A', 'P'),
 				'qty'			=> 1,
				'cost'			=> 120000,
				'icon'			=> 'treeman1an',
			    'pos_id'        => 204,
			)
		)
	)
);

// Create race ID index (key:val = id:race_name).
$raceididx = array();
foreach (array_keys($DEA) as $race) {
    $raceididx[$DEA[$race]['other']['race_id']] = $race;
}

$stars = array(

   /*
       Note: The numbering of star ids must begin at the value specified in ID_STARS_BEGIN from the header file
       Note: Do never change star ids after using stars in OBBLM.
   */

   'Barik Farblast' => array (
       'id'            => -5,
       'ma'            => 6,
       'st'            => 3,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 42, 45, 105, 58, 12, 59),
       'cost'          => 60000,
       'icon'          => 'star',
       'races'         => array(4),
   ),
   'Brick Far\'th (+ Grotty)' => array (
       'id'            => -6,
       'ma'            => 5,
       'st'            => 5,
       'ag'            => 2,
       'av'            => 9,
       'def'    => array (99, 94, 54, 44, 58, 59, 110),
       'cost'          => 290000,
       'icon'          => 'star',
       'races'         => array(1, 15, 16),
   ),
   'Grotty (included in Brick Far\'th)' => array (
       'id'            => -7,
       'ma'            => 6,
       'st'            => 2,
       'ag'            => 4,
       'av'            => 7,
       'def'    => array (99, 23, 104, 108),
       'cost'          => 0,
       'icon'          => 'star',
       'races'         => array(1, 15, 16),
   ),
   'Bomber Dribblesnot' => array (
       'id'            => -8,
       'ma'            => 6,
       'st'            => 2,
       'ag'            => 3,
       'av'            => 7,
       'def'    => array (99, 40, 93, 23, 100, 104, 105, 108),
       'cost'          => 60000,
       'icon'          => 'star',
       'races'         => array(6, 12),
   ),
   'Boomer Eziasson' => array (
       'id'            => -9,
       'ma'            => 4,
       'st'            => 3,
       'ag'            => 2,
       'av'            => 9,
       'def'    => array (99, 40, 1, 93, 100, 105, 59),
       'cost'          => 60000,
       'icon'          => 'star',
       'races'         => array(4, 14),
   ),
   'Count Luthor Von Drakenborg' => array (
       'id'            => -10,
       'ma'            => 6,
       'st'            => 5,
       'ag'            => 4,
       'av'            => 9,
       'def'    => array (99, 1, 23, 98, 103),
       'cost'          => 390000,
       'icon'          => 'star',
       'races'         => array(13, 17, 18),
   ),
   'Deeproot Strongbranch' => array (
       'id'            => -11,
       'ma'            => 2,
       'st'            => 7,
       'ag'            => 1,
       'av'            => 10,
       'def'    => array (99, 1, 54, 57, 58, 59, 110),
       'cost'          => 250000,
       'icon'          => 'star',
       'races'         => array(7),
   ),
   'Eldril Sidewinder' => array (
       'id'            => -12,
       'ma'            => 8,
       'st'            => 3,
       'ag'            => 4,
       'av'            => 7,
       'def'    => array (99, 20, 23, 98, 44, 8),
       'cost'          => 170000,
       'icon'          => 'star',
       'races'         => array(3, 5, 8, 20),
   ),
   'Flint Churnblade' => array (
       'id'            => -13,
       'ma'            => 5,
       'st'            => 3,
       'ag'            => 2,
       'av'            => 8,
       'def'    => array (99, 1, 95, 100, 105, 59),
       'cost'          => 100000,
       'icon'          => 'star',
       'races'         => array(4),
   ),
   'Fungus the Loon' => array (
       'id'            => -14,
       'ma'            => 4,
       'st'            => 7,
       'ag'            => 3,
       'av'            => 7,
       'def'    => array (99, 91, 54, 100, 105, 108),
       'cost'          => 80000,
       'icon'          => 'star',
       'races'         => array(6),
   ),
   'Grashnak Blackhoof' => array (
       'id'            => -15,
       'ma'            => 6,
       'st'            => 6,
       'ag'            => 2,
       'av'            => 8,
       'def'    => array (99, 5, 75, 54, 59),
       'cost'          => 310000,
       'icon'          => 'star',
       'races'         => array(1, 2, 15),
   ),
   'Griff Oberwald' => array (
       'id'            => -16,
       'ma'            => 7,
       'st'            => 4,
       'ag'            => 4,
       'av'            => 8,
       'def'    => array (99, 1, 23, 4, 28, 29),
       'cost'          => 320000,
       'icon'          => 'star',
       'races'         => array(9),
   ),
   'Grim Ironjaw' => array (
       'id'            => -17,
       'ma'            => 5,
       'st'            => 4,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 1, 2, 5, 54, 59),
       'cost'          => 220000,
       'icon'          => 'star',
       'races'         => array(4),
   ),
   'Hack Enslash' => array (
       'id'            => -18,
       'ma'            => 6,
       'st'            => 3,
       'ag'            => 2,
       'av'            => 7,
       'def'    => array (99, 95, 100, 103, 105, 26),
       'cost'          => 90000,
       'icon'          => 'star',
       'races'         => array(10, 13, 17),
   ),
   'Hakflem Skuttlespike' => array (
       'id'            => -19,
       'ma'            => 9,
       'st'            => 3,
       'ag'            => 4,
       'av'            => 7,
       'def'    => array (99, 23, 73, 76, 78),
       'cost'          => 200000,
       'icon'          => 'star',
       'races'         => array(19),
   ),
   'Headsplitter' => array (
       'id'            => -20,
       'ma'            => 6,
       'st'            => 6,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 5, 54, 76),
       'cost'          => 340000,
       'icon'          => 'star',
       'races'         => array(19),
   ),
   'Helmut Wulf' => array (
       'id'            => -21,
       'ma'            => 6,
       'st'            => 3,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 95, 100, 105, 57),
       'cost'          => 80000,
       'icon'          => 'star',
       'races'         => array(0, 8, 11, 14, 18),
   ),
   'Hemlock' => array (
       'id'            => -22,
       'ma'            => 8,
       'st'            => 2,
       'ag'            => 3,
       'av'            => 7,
       'def'    => array (99, 1, 23, 26, 24, 106, 108),
       'cost'          => 170000,
       'icon'          => 'star',
       'races'         => array(11),
   ),
   'Horkon Heartripper' => array (
       'id'            => -23,
       'ma'            => 7,
       'st'            => 3,
       'ag'            => 4,
       'av'            => 7,
       'def'    => array (99, 23, 25, 55, 10, 106),
       'cost'          => 210000,
       'icon'          => 'star',
       'races'         => array(3),
   ),
   'Hthark the Unstoppable' => array (
       'id'            => -24,
       'ma'            => 6,
       'st'            => 5,
       'ag'            => 2,
       'av'            => 9,
       'def'    => array (99, 1, 50, 53, 28, 29, 59),
       'cost'          => 310000,
       'icon'          => 'star',
       'races'         => array(2),
   ),
   'Hubris Rakarth' => array (
       'id'            => -25,
       'ma'            => 7,
       'st'            => 4,
       'ag'            => 4,
       'av'            => 8,
       'def'    => array (99, 1, 3, 24, 54, 11),
       'cost'          => 260000,
       'icon'          => 'star',
       'races'         => array(3, 5),
   ),
   'Icepelt Hammerblow' => array (
       'id'            => -26,
       'ma'            => 5,
       'st'            => 6,
       'ag'            => 1,
       'av'            => 8,
       'def'    => array (99, 71, 72, 5, 54, 103),
       'cost'          => 330000,
       'icon'          => 'star',
       'races'         => array(14),
   ),
   'Jordell Freshbreeze' => array (
       'id'            => -27,
       'ma'            => 8,
       'st'            => 3,
       'ag'            => 5,
       'av'            => 7,
       'def'    => array (99, 1, 21, 23, 25, 26),
       'cost'          => 230000,
       'icon'          => 'star',
       'races'         => array(5, 20),
   ),
   'Lord Borak the Despoiler' => array (
       'id'            => -28,
       'ma'            => 5,
       'st'            => 5,
       'ag'            => 3,
       'av'            => 9,
       'def'    => array (99, 1, 3, 54),
       'cost'          => 270000,
       'icon'          => 'star',
       'races'         => array(1, 15),
   ),
   'Max Spleenripper' => array (
       'id'            => -29,
       'ma'            => 5,
       'st'            => 4,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 95, 100, 105),
       'cost'          => 100000,
       'icon'          => 'star',
       'races'         => array(1, 15),
   ),
   'Mighty Zug' => array (
       'id'            => -30,
       'ma'            => 4,
       'st'            => 5,
       'ag'            => 2,
       'av'            => 9,
       'def'    => array (99, 1, 54),
       'cost'          => 230000,
       'icon'          => 'star',
       'races'         => array(9),
   ),
   'Morg \'n\' Thorg' => array (
       'id'            => -31,
       'ma'            => 6,
       'st'            => 6,
       'ag'            => 3,
       'av'            => 10,
       'def'    => array (99, 1, 54, 59, 110),
       'cost'          => 430000,
       'icon'          => 'star',
       'races'         => array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 14, 15, 16, 18, 19, 20),
   ),
   'Nobbla Blackwart' => array (
       'id'            => -32,
       'ma'            => 6,
       'st'            => 2,
       'ag'            => 3,
       'av'            => 7,
       'def'    => array (99, 1, 23, 95, 100, 105, 108),
       'cost'          => 100000,
       'icon'          => 'star',
       'races'         => array(2, 6, 16),
   ),
   'Prince Moranion' => array (
       'id'            => -33,
       'ma'            => 7,
       'st'            => 4,
       'ag'            => 4,
       'av'            => 8,
       'def'    => array (99, 1, 2, 13, 14),
       'cost'          => 230000,
       'icon'          => 'star',
       'races'         => array(5, 8),
   ),
   'Puggy Baconbreath' => array (
       'id'            => -34,
       'ma'            => 5,
       'st'            => 3,
       'ag'            => 3,
       'av'            => 6,
       'def'    => array (99, 1, 23, 44, 104, 108),
       'cost'          => 140000,
       'icon'          => 'star',
       'races'         => array(7, 9),
   ),
   'Ramtut III' => array (
       'id'            => -35,
       'ma'            => 5,
       'st'            => 6,
       'ag'            => 1,
       'av'            => 9,
       'def'    => array (99, 50, 54, 103, 14),
       'cost'          => 350000,
       'icon'          => 'star',
       'races'         => array(10, 13, 17),
   ),
   'Rashnak Backstabber' => array (
       'id'            => -36,
       'ma'            => 7,
       'st'            => 3,
       'ag'            => 3,
       'av'            => 7,
       'def'    => array (99, 23, 26, 27, 106),
       'cost'          => 200000,
       'icon'          => 'star',
       'races'         => array(2),
   ),
   'Ripper' => array (
       'id'            => -37,
       'ma'            => 4,
       'st'            => 6,
       'ag'            => 1,
       'av'            => 9,
       'def'    => array (99, 51, 54, 103, 110),
       'cost'          => 270000,
       'icon'          => 'star',
       'races'         => array(1, 6, 15, 12),
   ),
   'Scrappa Sorehead' => array (
       'id'            => -38,
       'ma'            => 7,
       'st'            => 2,
       'ag'            => 3,
       'av'            => 7,
       'def'    => array (99, 3, 23, 25, 104, 105, 28, 108, 29, 79),
       'cost'          => 50000,
       'icon'          => 'star',
       'races'         => array(6, 16, 12),
   ),
   'Setekh' => array (
       'id'            => -39,
       'ma'            => 6,
       'st'            => 4,
       'ag'            => 2,
       'av'            => 8,
       'def'    => array (99, 1, 50, 53, 103, 11),
       'cost'          => 220000,
       'icon'          => 'star',
       'races'         => array(10, 13, 17),
   ),
   'Slibli' => array (
       'id'            => -40,
       'ma'            => 7,
       'st'            => 4,
       'ag'            => 1,
       'av'            => 9,
       'def'    => array (99, 1, 51, 52, 57),
       'cost'          => 250000,
       'icon'          => 'star',
       'races'         => array(11),
   ),
   'Skitter Stab-Stab' => array (
       'id'            => -41,
       'ma'            => 9,
       'st'            => 2,
       'ag'            => 4,
       'av'            => 7,
       'def'    => array (99, 23, 76, 10, 106),
       'cost'          => 160000,
       'icon'          => 'star',
       'races'         => array(19),
   ),
   'Ugroth Bolgrot' => array (
       'id'            => -42,
       'ma'            => 5,
       'st'            => 3,
       'ag'            => 3,
       'av'            => 9,
       'def'    => array (99, 95, 100, 105),
       'cost'          => 70000,
       'icon'          => 'star',
       'races'         => array(12),
   ),
   'Varag Ghoul-Chewer' => array (
       'id'            => -43,
       'ma'            => 6,
       'st'            => 4,
       'ag'            => 3,
       'av'            => 9,
       'def'    => array (99, 1, 24, 54, 59),
       'cost'          => 260000,
       'icon'          => 'star',
       'races'         => array(12),
   ),
   'Wilhelm Chaney' => array (
       'id'            => -44,
       'ma'            => 8,
       'st'            => 4,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 20, 71, 5, 103, 14),
       'cost'          => 240000,
       'icon'          => 'star',
       'races'         => array(13, 14, 18),
   ),
   'Zara the Slayer' => array (
       'id'            => -45,
       'ma'            => 6,
       'st'            => 4,
       'ag'            => 3,
       'av'            => 8,
       'def'    => array (99, 1, 2, 23, 24, 106, 107),
       'cost'          => 270000,
       'icon'          => 'star',
       'races'         => array(0, 4, 9, 14),
   ),
   'Zzharg Madeye' => array (
       'id'            => -46,
       'ma'            => 4,
       'st'            => 4,
       'ag'            => 3,
       'av'            => 9,
       'def'    => array (99, 42, 45, 105, 58, 12, 13, 59),
       'cost'          => 60000,
       'icon'          => 'star',
       'races'         => array(2),
   )
);

$sparray = array (	
	'Rookie'	=> array (
		'SPP'	=> 0,
		'SPR'	=> 0	
	),
	'Experienced'	=> array (
		'SPP'	=> 6,
		'SPR'	=> 1
			
	),
	'Veteran'	=> array (
		'SPP'	=> 16,
		'SPR'	=> 2

	),
	'Emerging Star'	=> array (
		'SPP'	=> 31,
		'SPR'	=> 3	

	),
	'Star'	=> array (
		'SPP'	=> 51,
		'SPR'	=> 4	
	),
	'Super Star'	=> array (
		'SPP'	=> 76,
		'SPR'	=> 5	
	),
	'Legend'	=> array (
		'SPP'	=> 176,
		'SPR'	=> 6
	)
);

$skillarray	= array (	
    # ID => "skill name"
    # Note jumps in ID numbering, this allowed future skills to be added still maintaining some senseable ordering.
	'G'	=> array (
		1  => 'Block',
		2  => 'Dauntless',
		3  => 'Dirty Player',
		4  => 'Fend',
		5  => 'Frenzy',
		6  => 'Kick',
		7  => 'Kick-Off Return',
		8  => 'Pass Block',
		9  => 'Pro',
		10 => 'Shadowing',
		11 => 'Strip Ball',
		12 => 'Sure Hands',
		13 => 'Tackle',
		14 => 'Wrestle',
	),
	'A'	=> array (
		20 => 'Catch',
		21 => 'Diving Catch',
		22 => 'Diving Tackle',
		23 => 'Dodge',
		24 => 'Jump Up',
		25 => 'Leap',
		26 => 'Side Step',
		27 => 'Sneaky Git',
		28 => 'Sprint',
		29 => 'Sure Feet',
	),
	'P'	=> array (
		40 => 'Accurate',
		41 => 'Dump-Off',
		42 => 'Hail Mary Pass',
		43 => 'Leader',
		44 => 'Nerves of Steel',
		45 => 'Pass',
		46 => 'Safe Throw',
	),
	'S'	=> array (
		50 => 'Break Tackle',
		51 => 'Grab',
		52 => 'Guard',
		53 => 'Juggernaut',
		54 => 'Mighty Blow',
		55 => 'Multiple Block',
		56 => 'Piling On',
		57 => 'Stand Firm',
		58 => 'Strong Arm',
		59 => 'Thick Skull',
	),
	'M'	=> array (
		70 => 'Big Hand',
		71 => 'Claw/Claws',
		72 => 'Disturbing Presence',
		73 => 'Extra Arms',
		74 => 'Foul Appearance',
		75 => 'Horns',
		76 => 'Prehensile Tail',
		77 => 'Tentacles',
		78 => 'Two Heads',
		79 => 'Very Long Legs',
	),
	# Extraordinay
	'E'	=> array (
		90 => 'Always Hungry',
		91 => 'Ball & Chain',
		92 => 'Blood Lust',
		93 => 'Bombardier',
		94 => 'Bone-Head',
		95 => 'Chainsaw',
		96 => 'Decay',
		97 => 'Fan Favourite',
		98 => 'Hypnotic Gaze',
		99 => 'Loner',
		100 => 'No Hands',
		101 => "Nurgle's Rot",
		102 => 'Really Stupid',
		103 => 'Regeneration',
		104 => 'Right Stuff',
		105 => 'Secret Weapon',
		106 => 'Stab',
		107 => 'Stakes',
		108 => 'Stunty',
		109 => 'Take Root',
		110 => 'Throw Team-Mate',
		111 => 'Titchy',
		112 => 'Wild Animal',
	),
);

// Create skill ID index (key:val = id:skill_name).
$skillididx = array();
foreach ($skillarray as $grp => $skills) {
    foreach ($skills as $id => $name)
        $skillididx[$id] = $name;
}

$IllegalSkillCombinations = array(
    /*
        Syntax:
        "If player has this skill" => array("player may not have this skill", "or this skills", ...),
    */
    5   => array(51),
    51  => array(5),
    91  => array(22, 5, 7, 8, 10),
);

// Instead of purchasing an Apothecary, Necromantic and Undead teams use the services of a Necromancer. 
// This means these teams may also recieve free zombies.
$racesHasNecromancer = array(T_RACE_NECROMANTIC, T_RACE_UNDEAD);
// Khemri, Necromantic, Nurgle and Undead teams may not purchase or use an Apothecary.
$racesNoApothecary = array_merge($racesHasNecromancer, array(T_RACE_NURGLE, T_RACE_KHEMRI));
// Nurgles players with Nurgle's Rot may raise rotters. Really, this only applies for _players_ (not the race) with the skill "Nurgle's Rot".
$racesMayRaiseRotters = array(T_RACE_NURGLE);

$inducements = array (
    'Bloodweiser Babes' => array (
        'cost' => 50000,
        'max'  => 2,
        'reduced_cost' => 50000,
        'reduced_cost_races' => array(),
    ),
    'Bribes' => array (
        'cost' => 100000,
        'max'  => 3,
        'reduced_cost' => 100000,
        'reduced_cost_races' => array(),
    ),
    'Extra Training' => array (
        'cost' => 100000,
        'max'  => 4,
        'reduced_cost' => 100000,
        'reduced_cost_races' => array(),
    ),
    'Halfling Master Chef' => array (
        'cost' => 300000,
        'max'  => 1,
        'reduced_cost' => 100000,
        'reduced_cost_races' => array(7), # Halflings
    ),
    'Wandering Apothecaries' => array (
        'cost' => 100000,
        'max'  => 2,
        'reduced_cost' => 100000,
        'reduced_cost_races' => array(),
    ),
    # Igor is only buyable by the teams in $racesNoApothecary from above
    'Igor' => array (
        'cost' => 100000,
        'max'  => 1,
        'reduced_cost' => 100000,
        'reduced_cost_races' => array(),
    ),
    'Wizard' => array (
        'cost' => 150000,
        'max'  => 1,
        'reduced_cost' => 150000,
        'reduced_cost_races' => array(),
    )
);

?>
