<?php

$_t_player_types_skill_normal = 
'
DROP TABLE IF EXISTS "Player_Type_Skill_Categories_Normal";
CREATE TABLE Player_Type_Skill_Categories_Normal (ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,idPlayer_Types INTEGER ,idSkill_Categories INTEGER ,DESCRIPTION VARCHAR(255) );
';

$_dat_skill_normal =
"
INSERT INTO player_type_skill_categories_normal VALUES (1, 1, 1, 'Human Lineman General');
INSERT INTO player_type_skill_categories_normal VALUES (2, 2, 1, 'Human Catcher General');
INSERT INTO player_type_skill_categories_normal VALUES (3, 2, 2, 'Human Catcher Agility');
INSERT INTO player_type_skill_categories_normal VALUES (4, 3, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (5, 3, 3, '');
INSERT INTO player_type_skill_categories_normal VALUES (6, 4, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (7, 4, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (8, 5, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (9, 6, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (10, 6, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (11, 7, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (12, 7, 3, '');
INSERT INTO player_type_skill_categories_normal VALUES (13, 8, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (14, 8, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (15, 9, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (16, 9, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (17, 10, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (18, 11, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (19, 11, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (20, 12, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (21, 12, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (22, 13, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (23, 13, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (24, 13, 3, '');
INSERT INTO player_type_skill_categories_normal VALUES (25, 14, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (26, 14, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (27, 15, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (28, 16, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (29, 17, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (30, 17, 3, '');
INSERT INTO player_type_skill_categories_normal VALUES (31, 18, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (32, 18, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (33, 19, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (34, 19, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (35, 20, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (36, 21, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (37, 22, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (38, 23, 3, '');
INSERT INTO player_type_skill_categories_normal VALUES (39, 23, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (40, 24, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (41, 24, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (42, 25, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (43, 25, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (44, 26, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (45, 27, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (46, 28, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (47, 28, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (48, 29, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (49, 30, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (50, 31, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (51, 32, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (52, 33, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (53, 33, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (54, 33, 5, '');
INSERT INTO player_type_skill_categories_normal VALUES (56, 34, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (57, 34, 5, '');
INSERT INTO player_type_skill_categories_normal VALUES (60, 44, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (61, 32, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (62, 32, 5, '');
INSERT INTO player_type_skill_categories_normal VALUES (64, 45, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (65, 46, 4, '');
INSERT INTO player_type_skill_categories_normal VALUES (66, 47, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (67, 47, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (68, 48, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (69, 48, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (70, 48, 3, '');
INSERT INTO player_type_skill_categories_normal VALUES (71, 49, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (72, 49, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (73, 50, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (74, 50, 2, '');
INSERT INTO player_type_skill_categories_normal VALUES (75, 51, 1, '');
INSERT INTO player_type_skill_categories_normal VALUES (76, 51, 2, '');
";

global $settings;
if ($settings['leegmgr_cyanide_edition'] == 2) {
    $_dat_skill_normal .= "
INSERT INTO player_type_skill_categories_normal VALUES (77, 54,	1, 'Undead Skeleton General');			
INSERT INTO player_type_skill_categories_normal VALUES (78, 55,	1, 'Undead Zombie General');			
INSERT INTO player_type_skill_categories_normal VALUES (79, 56,	1, 'Undead Ghoul General');			
INSERT INTO player_type_skill_categories_normal VALUES (80, 56,	2, 'Undead Ghoul Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (81, 57,	1, 'Undead Wight General');			
INSERT INTO player_type_skill_categories_normal VALUES (82, 57,	4, 'Undead Wight Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (83, 58,	4, 'Undead Mummy Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (94, 60,	2, 'Halfling Halfling Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (95, 61,	4, 'Hafling Treeman Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (96, 62,	1, 'Norse Lineman General');			
INSERT INTO player_type_skill_categories_normal VALUES (97, 63,	1, 'Norse Thrower General');			
INSERT INTO player_type_skill_categories_normal VALUES (98, 63,	3, 'Norse Thrower Passing');			
INSERT INTO player_type_skill_categories_normal VALUES (99, 64,	1, 'Norse Runner General');			
INSERT INTO player_type_skill_categories_normal VALUES (100, 64, 2, 'Norse Runner Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (101, 65, 1, 'Norse Berserker General');			
INSERT INTO player_type_skill_categories_normal VALUES (102, 65, 4, 'Norse Berserker Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (103, 66, 1, 'Norse Ulfwerener General');			
INSERT INTO player_type_skill_categories_normal VALUES (104, 66, 4, 'Norse Ulfwerener Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (105, 67, 4, 'Norse Yhetee Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (106, 68, 1, 'Amazon Linewomen General');			
INSERT INTO player_type_skill_categories_normal VALUES (107, 69, 1, 'Amazon Thrower General');			
INSERT INTO player_type_skill_categories_normal VALUES (108, 69, 3, 'Amazon Thrower Passing');			
INSERT INTO player_type_skill_categories_normal VALUES (109, 70, 1, 'Amazon Catcher General');			
INSERT INTO player_type_skill_categories_normal VALUES (110, 70, 2, 'Amazon Catcher Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (111, 71, 1, 'Amazon Blitzer General');			
INSERT INTO player_type_skill_categories_normal VALUES (112, 71, 4, 'Amazon Blitzer Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (113, 72, 1, 'Elf Lineman General');			
INSERT INTO player_type_skill_categories_normal VALUES (114, 72, 2, 'Elf Lineman Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (115, 73, 1, 'Elf Thrower General');			
INSERT INTO player_type_skill_categories_normal VALUES (116, 73, 2, 'Elf Thrower Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (117, 73, 3, 'Elf Thrower Passing');			
INSERT INTO player_type_skill_categories_normal VALUES (118, 74, 1, 'Elf Catcher General');			
INSERT INTO player_type_skill_categories_normal VALUES (119, 74, 2, 'Elf Catcher Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (120, 75, 1, 'Elf Blitzer General');			
INSERT INTO player_type_skill_categories_normal VALUES (121, 75, 2, 'Elf Blitzer Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (122, 77, 1, 'High Elf Lineman General');			
INSERT INTO player_type_skill_categories_normal VALUES (123, 77, 2, 'High Elf Lineman Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (124, 78, 1, 'High Elf Thrower General');			
INSERT INTO player_type_skill_categories_normal VALUES (125, 78, 2, 'High Elf Thrower Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (126, 78, 3, 'High Elf Thrower Passing');			
INSERT INTO player_type_skill_categories_normal VALUES (127, 79, 1, 'High Elf Catcher General');			
INSERT INTO player_type_skill_categories_normal VALUES (128, 79, 2, 'High Elf Catcher Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (129, 80, 1, 'High Elf Blitzer General');			
INSERT INTO player_type_skill_categories_normal VALUES (130, 80, 2, 'High Elf Blitzer Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (131, 81, 1, 'Khemri Skeleton General');			
INSERT INTO player_type_skill_categories_normal VALUES (132, 82, 1, 'Khemri Thro-Ra General');			
INSERT INTO player_type_skill_categories_normal VALUES (133, 82, 3, 'Khemri Thro-Ra Passing');			
INSERT INTO player_type_skill_categories_normal VALUES (134, 83, 1, 'Khemri Blitz-Ra General');			
INSERT INTO player_type_skill_categories_normal VALUES (135, 83, 4, 'Khemri Blitz-Ra Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (136, 84, 4, 'Khemri Tomb Guardian Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (137, 86, 1, 'Necromantic Zombie General');			
INSERT INTO player_type_skill_categories_normal VALUES (138, 87, 1, 'Necromantic Ghoul General');			
INSERT INTO player_type_skill_categories_normal VALUES (139, 87, 2, 'Necromantic Ghoul Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (140, 88, 1, 'Necromantic Wight General');			
INSERT INTO player_type_skill_categories_normal VALUES (141, 88, 4, 'Necromantic Wight Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (142, 89, 1, 'Necromantic Flesh Golem General');			
INSERT INTO player_type_skill_categories_normal VALUES (143, 89, 4, 'Necromantic Flesh Golem Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (144, 90, 1, 'Necromantic Werewolf General');			
INSERT INTO player_type_skill_categories_normal VALUES (145, 90, 2, 'Necromantic Werewolf Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (146, 91, 1, 'Nurgle Rotter General');			
INSERT INTO player_type_skill_categories_normal VALUES (147, 91, 5, 'Nurgle Rotter Mutation');			
INSERT INTO player_type_skill_categories_normal VALUES (148, 92, 1, 'Nurgle Pestigor General');			
INSERT INTO player_type_skill_categories_normal VALUES (149, 92, 4, 'Nurgle Pestigor Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (150, 92, 5, 'Nurgle Pestigor Mutation');			
INSERT INTO player_type_skill_categories_normal VALUES (151, 93, 1, 'Nurgle Warrior General');			
INSERT INTO player_type_skill_categories_normal VALUES (152, 93, 4, 'Nurgle Warrior Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (153, 93, 5, 'Nurgle Warrior Mutation');			
INSERT INTO player_type_skill_categories_normal VALUES (154, 94, 4, 'Nurgle Beast of Nurgle Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (155, 95, 2, 'Ogre Snotling Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (156, 96, 4, 'Ogre Ogre Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (157, 97, 1, 'Vampire Thrall General');			
INSERT INTO player_type_skill_categories_normal VALUES (158, 98, 1, 'Vampire Vampire General');			
INSERT INTO player_type_skill_categories_normal VALUES (159, 98, 2, 'Vampire Vampire Agility');			
INSERT INTO player_type_skill_categories_normal VALUES (160, 98, 4, 'Vampire Vampire Strength');			
INSERT INTO player_type_skill_categories_normal VALUES (161, 107, 2, 'Goblin Bombardier Agility');
";
}
?>
